<?php 
$title = 'Login - O Uivo da Noite';
$style = 'login';
require 'template.phtml';
?>

<body>

  <div class="container">

    <div class="logo">
      <div>
        <a href="#">Login com <span class="google">Google</span></a>
      </div>

      <div>
        <a href="#">Login com <span class="facebook">Facebook</span></a>
      </div>
    </div>

    <div class="login">

      <img src="/public/assets/wolf-logo.png" alt="Logo">

      <div class="login-content">
        <span class="login-title">Login</span>

        <form action="/autenticar?action=login" method="post">

          <label for="email">E-mail</label>
          <input type="email" name="email" id="email" placeholder="Digite seu e-mail">
          <div class="line"></div>

          <label for="password">Senha</label>
          <input type="password" name="password" id="password" placeholder="Digite sua senha">
          <div class="line"></div>

          <button type="submit">Logar</button>

        </form>

        <?php
      
          if(isset($_SERVER['QUERY_STRING'])) {
            $error = explode('=', $_SERVER['QUERY_STRING']);

            foreach($error as $value) {
              if ($value == 'empty') {
                echo '<p class="login-error">Campo(s) não estão preenchido(s)</p>';
              }
  
              if ($value == 'noAuth') {
                echo '<p class="login-error">E-mail e/ou senha incorreto(s)</p>';
              }
            }
          }
         
        ?>

        <a href="/"><i class="fas fa-arrow-left fa-3x"></i></a>
      </div>

    </div>

  </div>

</body>